services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: "smart-home-timescaledb"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always
    volumes:
      - ./data/timescale:/var/lib/postgresql/data
      - ./sql/init-timescale.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  api:
    image: smart-home-hub-api:latest
    build: .
    container_name: "smart-home-hub-api"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 3
      rollback_config:
        failure_action: pause
        order: start-first
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        max_failure_ratio: 3
        order: start-first
    ports:
      - "5000:5000"
