name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy & Build
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Check out repository into Raspberry Pi
        uses: actions/checkout@v4

      - name: Docker Compose Up
        run: |
          rsync -av --exclude='/home/pi/Projects/smart-home-hub/.git' $GITHUB_WORKSPACE/ /home/pi/Projects/smart-home-hub/
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > /home/pi/Projects/smart-home-hub/.env
          cd /home/pi/Projects/smart-home-hub/
          sudo docker compose up --build -d timescaledb --force-recreate
          sudo docker compose up --build -d api
          sudo docker system prune -f
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}