name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy & Build
    runs-on: self-hosted
    steps:
      - name: Check out repository into Raspberry Pi
        uses: actions/checkout@v4
